# конфигурация spring-профиля "jpa-dev"
# отключает liquibase
# включает миграцию через jpa, создаст таблицы бд, которые можно будет забрать по liquibase diff
# выполняет бин DatabaseInitializer
# разрешает работу кук по http

server:
  servlet:
    session:
      cookie:
        secure: false
        same-site: lax

spring:
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  liquibase:
    enabled: false

app:
  scheduling:
    cron: 0 */1 * * * *
    enabled: true