# конфигурация spring-профиля "dev"
# переводит liquibase в режим drop-first (очистка БД перед миграцией)
# проводит миграцию liquibase, включая testdata.xml
# выполняет бин DatabaseInitializer
# разрешает работу кук по http

server:
  servlet:
    session:
      cookie:
        secure: false
        same-site: lax

spring:
  jpa:
    show-sql: true
  liquibase:
    contexts: dev
    drop-first: true

  app:
    scheduling:
      cron: 0 */1 * * * *
      enabled: true