spring:
  data:
    rest:
      base-path: /
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
    url: jdbc:postgresql://localhost:5432/lakomka
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
#      ddl-auto: create
      ddl-auto: create-drop
